routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
    Route::get('/admin', function () {
        return view('admin.index');
    });

    Route::get('post/{id}', ['as' => 'view.post', 'uses' => 'AdminPostsController@show']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'is_active', 'photo_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function photo()
    {
        return $this->belongsTo('App\Photo');
    }

    public function isAdmin()
    {
        return $this->role->name == 'administrator' && $this->is_active == 1 ? true : false;
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    /*
     * get Attribute function mutator can be used to create fake db columns
     * ?d=mm for default
     * &s for size
     */
    public function getGravatarAttribute()
    {
        $hash = md5(strtolower(trim($this->attributes['email']))) . "?d=mm";
        return "http://gravatar.com/avatar/$hash";
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin') @section('content')
<h1>Create User</h1>

{!! Form::open(['method'=>'POST', 'action'=>'AdminUsersController@store', 'files'=>true]) !!}
<div class="form-group">
	{!! Form::label('name', 'Name') !!} {!! Form::text('name', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('email', 'Email') !!} {!! Form::email('email', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('role_id', 'Role') !!} {!! Form::select('role_id', [''=>'Choose an Option'] + $roles, null, ['class'=>'form-control'])
	!!}
</div>
<div class="form-group">
	{!! Form::label('photo', 'Image') !!} {!! Form::file('photo', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('is_active', 'Status') !!} {!! Form::select('is_active',array(1=>'Active', 0=> 'Not Active'), 0, ['class'=>'form-control'])
	!!}
</div>
<div class="form-group">
	{!! Form::label('password', 'Password') !!} {!! Form::password('password', ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
</div>
{!! Form::close() !!} @include('includes.form_error') @endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin') @section('content')
<div class="col-sm-12">
	<h1>Edit User</h1>
</div>

<div class="row">
	<div class="col-sm-3">
		<img src="{{ !empty($user->photo)? asset($user->photo->file) : 'http://placehold.it/400x400' }}" class="img-responsive img-rounded"
		/>
	</div>
	<div class="col-sm-9">
		{!! Form::model($user, ['method'=>'PATCH', 'action'=>['AdminUsersController@update', $user->id], 'files'=>true]) !!}

		<div class="form-group">
			{!! Form::label('name', 'Name') !!} {!! Form::text('name', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('email', 'Email') !!} {!! Form::email('email', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('role_id', 'Role') !!} {!! Form::select('role_id', [''=>'Choose an Option'] + $roles, null, ['class'=>'form-control'])
			!!}
		</div>
		<div class="form-group">
			{!! Form::label('photo', 'Image') !!} {!! Form::file('photo', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('is_active', 'Status') !!} {!! Form::select('is_active',array(1=>'Active', 0=> 'Not Active'), null, ['class'=>'form-control'])
			!!}
		</div>
		<div class="form-group">
			{!! Form::label('password', 'Password') !!} {!! Form::password('password', ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Update User', ['class'=>'btn btn-primary']) !!}
		</div>
    {!! Form::close() !!} 
    {!! Form::open(['method'=>'DELETE', 'action'=>['AdminUsersController@destroy', $user->id], 'files'=>true]) !!}
		<div class="form-group">
			{!! Form::submit('Delete User', ['class'=>'btn btn-danger']) !!}
		</div>
		{!! Form::close() !!}
	</div>
</div>
<div class="row">
	@include('includes.form_error')
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin') @section('content')
 @if(Session::has('deleted_user')) 
 <p class="alert alert-danger">{{ session('deleted_user') }}</p>
  @endif
<h1>Users</h1>
<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Photo</th>
			<th>Name</th>
			<th>Email</th>
			<th>Role</th>
			<th>Status</th>
			<th>Created</th>
			<th>Updated</th>
		</tr>
	</thead>
	<tbody>
		@if($users) @foreach($users as $user)
		<tr>
			<td>{{$user->id}}</td>
			<td>@if($user->photo)
				<img src="{{ asset($user->photo->file) }} " height="50px" /> @endif 
				<img src="{{ asset($user->gravatar) }} " height="50px" />
			</td>
			<td>
				<a href="{{ route('users.edit', $user->id) }}">{{$user->name}}</a>
			</td>
			<td>{{$user->email}}</td>
			<td>{{ $user->role != null ? $user->role->name : 'no role'}}</td>
			<td>{{$user->is_active == 1 ? 'Active': 'Not active'}}</td>
			<td>{{$user->created_at->diffForHumans()}}</td>
			<td>{{$user->updated_at->diffForHumans()}}</td>
		</tr>
		@endforeach @endif
	</tbody>
</table>
@endsection