routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
    Route::get('/admin', function () {
        return view('admin.index');
    });

    Route::get('post/{id}', ['as' => 'view.post', 'uses' => 'AdminPostsController@show']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['user_id','category_id', 'photo_id', 'title', 'body'];

    public function user(){
        return $this->belongsTo('App\User');
    }
    public function photo(){
        return $this->belongsTo('App\Photo');
    }
    public function category(){
        return $this->belongsTo('App\Category');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }
}

resources/views/admin/posts/create.blade.php
@extends('layouts.admin') @section('content')
@include('includes.tinymceditor')
<h1>Create Post</h1>

{!! Form::open(['method'=>'POST', 'action'=>'AdminPostsController@store', 'files'=>true]) !!}
<div class="form-group">
	{!! Form::label('title', 'Title') !!} {!! Form::text('title', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('category_id', 'Category') !!} {!! Form::select('category_id', [''=>'Choose an Option']+$categories, null,
	['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('photo_id', 'Photo') !!} {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::label('body', 'Description') !!} {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
</div>
<div class="form-group">
	{!! Form::submit('Create Post', ['class'=>'btn btn-primary']) !!}
</div>
{!! Form::close() !!} @include('includes.form_error') @endsection

resources/views/admin/posts/edit.blade.php
@extends('layouts.admin') @section('content')
@include('includes.tinymceditor')
<h1>Edit Post</h1>

<div class="row">
	<div class="col-sm-3">
		<img src="{{ !empty($post->photo)? asset($post->photo->file) : 'http://placehold.it/400x400' }}" class="img-responsive img-rounded"
		/>
	</div>

	<div class="col-sm-9">
		{!! Form::model($post, ['method'=>'PATCH', 'action'=>['AdminPostsController@update', $post->id], 'files'=>true]) !!}
		<div class="form-group">
			{!! Form::label('title', 'Title') !!} {!! Form::text('title', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('category_id', 'Category') !!} {!! Form::select('category_id', [''=>'Choose an Option']+$categories, null,
			['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('photo_id', 'Photo') !!} {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('body', 'Description') !!} {!! Form::textarea('body', null, ['class'=>'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit('Update Post', ['class'=>'btn btn-primary col-sm-6']) !!}
		</div>
		{!! Form::close() !!} {!! Form::open(['method'=>'DELETE', 'action'=>['AdminPostsController@destroy', $post->id]])
		!!}
		<div class="form-group">
			{!! Form::submit('Delete Post', ['class'=>'btn btn-danger col-sm-6']) !!}
		</div>
		{!! Form::close() !!}
	</div>
</div>
<div class="row">
	@include('includes.form_error')
</div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.admin') @section('content') @if(Session::has('deleted_post'))
<p class="alert alert-danger">{{ session('deleted_post') }}</p>
@endif
<h1>Posts</h1>
<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>User</th>
			<th>Photo</th>
			<th>Category</th>
			<th>Title</th>
			<th>Body</th>
			<th>View Post</th>
			<th>View Comments</th>
			<th>Created</th>
			<th>Updated</th>
		</tr>
	</thead>
	<tbody>
		@if($posts) @foreach($posts as $post)
		<tr>
			<td>{{$post->id}}</td>
			<td>{{ $post->user->name}}</td>
			<td>
				@if($post->photo)
				<img src="{{ asset($post->photo->file) }} " height="50px" /> @else
				<img src="http://placehold.it/50x50" /> @endif
			</td>
			<td>{{ $post->category != null ? $post->category->name : 'uncategorized'}}</td>
			<td>
				<a title="edit post" href="{{ route('posts.edit', $post->id) }}">{{ $post->title}}</a>
			</td>
			<td>{!! str_limit(strip_tags($post->body), 30) !!}</td>
			<td>
				<a href="{{ route('view.post', $post->id) }}">View Post</a>
			</td>
			<td>
				<a href="{{route('comments.show', $post->id)}}">View Comment</a>
			</td>

			<td>{{$post->created_at->diffForHumans()}}</td>
			<td>{{$post->updated_at->diffForHumans()}}</td>
		</tr>
		@endforeach @endif
	</tbody>
</table>
<div class="row">
	<div class="col-sm-6 col-sm-offset-5">
		{{$posts->render()}}
	</div>
</div>
@endsection