routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
    Route::resource('admin/posts', 'AdminPostsController');
    Route::resource('admin/categories', 'AdminCategoriesController');
    Route::resource('admin/medias', 'AdminMediasController');
    Route::resource('admin/comments', 'PostCommentsController');
    Route::resource('admin/comment/replies', 'CommentRepliesController');
    Route::get('/admin', function () {
        return view('admin.index');
    });

    Route::get('post/{id}', ['as' => 'view.post', 'uses' => 'AdminPostsController@show']);
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('comment/reply', 'CommentRepliesController@createReply');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin') @section('content') @if(Session::has('deleted_category'))
<p class="alert alert-danger">{{ session('deleted_category') }}</p>
@endif
<h1>Edit Category</h1>
<div class="col-sm-6">
	{!! Form::model($category, ['method'=>'PATCH', 'action'=>['AdminCategoriesController@update', $category->id]]) !!}
	<div class="form-group">
		{!! Form::label('name', 'Name') !!} {!! Form::text('name', null, ['class'=>'form-control']) !!}
	</div>
	<div class="form-group">
		{!! Form::submit('Update Category', ['class'=>'btn btn-primary col-sm-6']) !!}
	</div>
	{!! Form::close() !!} {!! Form::open(['method'=>'DELETE', 'action'=>['AdminCategoriesController@destroy', $category->id]]) !!}
	<div class="form-group">
		{!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6']) !!}
	</div>
	{!! Form::close() !!} @include('includes.form_error') @endsection
</div>

resources/views/admin/categories/index.blade.php
@extends('layouts.admin') @section('content') @if(Session::has('deleted_category'))
<p class="alert alert-danger">{{ session('deleted_category') }}</p>
@endif
<h1>Categories</h1>
<div class="col-sm-6">
	{!! Form::open(['method'=>'POST', 'action'=>'AdminCategoriesController@store']) !!}
	<div class="form-group">
		{!! Form::label('name', 'Name') !!} {!! Form::text('name', null, ['class'=>'form-control']) !!}
	</div>
	<div class="form-group">
		{!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
	</div>
	{!! Form::close() !!} @include('includes.form_error')
</div>
<div class="col-sm-6">
	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Created</th>
				<th>Updated</th>
			</tr>
		</thead>
		<tbody>
			@if($categories) @foreach($categories as $category)
			<tr>
				<td>{{$category->id}}</td>
				<td><a href="{{ route('categories.edit', $category->id) }}">{{ $category->name}}</a></td>
				<td>
					@if($category->created_at) {{$category->created_at->diffForHumans()}} @endif
				</td>
				<td>
					@if($category->updated_at) {{$category->updated_at->diffForHumans()}} @endif
				</td>
			</tr>
			@endforeach @endif
		</tbody>
	</table>
</div>
@endsection